fix Makefile.test262

diff --git a/Makefile.test262 b/Makefile.test262
--- a/Makefile.test262
+++ b/Makefile.test262
@@ -1,5 +1,9 @@
+SHELL=/bin/bash
+
+ifeq ($(shell test -d test262; echo $$?),0)
 TEST262_CORE_POSITIVE?=$(shell find test262/test/suite/ch{08,09,10,11,12,13,14} -name '*.js' -exec grep -L '@negative' {} \;)
 TEST262_CORE_NEGATIVE?=$(shell find test262/test/suite/ch{08,09,10,11,12,13,14} -name '*.js' -exec grep -q '@negative' {} \; -print)
+endif
 
 .PHONY: test262-core
 test262-core: test262-core-positive test262-core-negative
@@ -10,16 +14,25 @@ test262-core-positive: $(TEST262_CORE_POSITIVE:%=%.out.positive)
 .PHONY: test262-core-negative
 test262-core-negative: $(TEST262_CORE_NEGATIVE:%=%.out.negative)
 
-%.js.out.positive: %.js.out
-	grep -q 'Empty substitution' $< && echo "#### $*.js succeed" || echo "#### $*.js failed"
-	rm -f $<
+%.js.out.positive:
+	$(call krun-test262,$*.js,"positive")
 
-%.js.out.negative: %.js.out
-	grep -L 'Empty substitution' $< && echo "#### $*.js succeed" || echo "#### $*.js failed"
-	rm -f $<
+%.js.out.negative:
+	$(call krun-test262,$*.js,"negative")
 
-%.js.out: %.js
-	-cat prelude.js $< >$<.prelude
-	-./jsmassage.sh -f $<.prelude >$<.prelude.massage
-	-krun -d . --pattern-matching --pattern "<k> @Normal </k>" $<.prelude.massage >$@ 2>&1
-	-rm -f $<.prelude $<.prelude.massage
+define krun-test262
+( cat prelude.js $(1) >$(1).prelude && \
+  ./jsmassage.sh -f $(1).prelude >$(1).prelude.massage && \
+  krun -d . --pattern-matching --pattern "<k> @Normal </k>" $(1).prelude.massage >$(1).out 2>&1 && \
+  grep -q 'Empty substitution' $(1).out; \
+  echo $$? >$(1).exitcode )
+@if [ $(2) = "positive" ]; then \
+  [ `cat $(1).exitcode` -eq 0 ] && echo "#### $(1) succeed" || echo "#### $(1) failed"; \
+else \
+  [ `cat $(1).exitcode` -eq 0 ] && echo "#### $(1) failed" || echo "#### $(1) succeed"; \
+fi
+endef
+
+.PHONY: test262-clean
+test262-clean:
+	find test262/test/suite/ch{08,09,10,11,12,13,14} -name '*.js.*' -exec rm -f {} \;
